# all commands by default will run on every commit
default_install_hook_types: [pre-commit]
default_stages: [commit]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.4.5
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-snowflake==1.3.0',
          'sqlfluff-templater-dbt==1.4.5'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-snowflake==1.3.0',
          'sqlfluff-templater-dbt==1.4.5'
        ]